#!/usr/bin/env python

import rospy

rospy.init_node("constant_setter")

rospy.set_param("teamid", "ASV")
rospy.set_param("course", "courseA")
rospy.set_param("server_host", "http://localhost:8080")

